#! /bin/sh
### BEGIN INIT INFO
# Provides:          m4ed upload worker
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: m4ed upload worker - Generator: m4ed fabfile
# Description:       m4ed upload worker - Generator: m4ed fabfile
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC=m4ed_upload_worker
USER=[[worker_user]]
GROUP=[[worker_group]]
PYTHON=[[worker_python]]
DAEMON=[[init_sbin_path]]
CONFFILE=[[worker_config]]
DAEMON_ARGS="$CONFFILE"
NAME=[[init_name]]
PIDFILE=[[init_pid_path]]
SCRIPTNAME=[[init_script_name]]

([ -x $PYTHON ] && [ -e $DAEMON ]) || exit 0

. /lib/init/vars.sh

. /lib/lsb/init-functions

do_start()
{
    touch $PIDFILE
    chown $USER:$USER $PIDFILE
    start-stop-daemon --start --quiet -b -m --chuid $USER:$GROUP --umask 002 --pidfile $PIDFILE --exec $PYTHON $DAEMON -- $DAEMON_ARGS
    RETVAL="$?"
    return "$RETVAL"
}

do_stop()
{
    # Return
    #   0 if daemon has been stopped
    #   1 if daemon was already stopped
    #   2 if daemon could not be stopped
    #   other if a failure occurred
    #   send --signal SIGINT with retry value to terminate mercifully
    start-stop-daemon --stop --quiet --signal INT --pidfile $PIDFILE
    RETVAL="$?"
    rm -f $PIDFILE
    return "$RETVAL"
}

case "$1" in
    start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC " "$NAME"
        do_start
        case "$?" in
            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
    stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        case "$?" in
            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
    status)
        status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    restart)
        log_daemon_msg "Restarting $DESC" "$NAME"
        do_stop
        case "$?" in
            0|1)
                do_start
                case "$?" in
                    0) log_end_msg 0 ;;
                    1) log_end_msg 1 ;; # Old process is still running
                    *) log_end_msg 1 ;; # Failed to start
                esac
                ;;
            *)
                # Failed to stop
                log_end_msg 1
                ;;
        esac
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
        exit 3
        ;;
esac

exit $RETVAL

